[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"
healthcheckPath = ""
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[experimental]
configAsCode = true